version: '3.9'

services:
  bot:
    build: .
    container_name: sd_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DB_FILE_PATH=/app/data/bot.db
    volumes:
      - /root/sd_bot_db:/app/data